mohanad/mohanad/urls.py
from django.conf.urls import url
from django.contrib import admin
from crm import views
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
#from pages.views import home_view, contact_view

urlpatterns = [
url(r'^Dashboard/$', views.home_view, name='home'),
url(r'^customer/$', views.customer_view, name='customer'),
url(r'^search/$', views.search_view, name='search'),
url(r'^newcustomer$', views.new_customer, name='newcustomer'),
url(r'^newservice$', views.new_service, name='newservice'),
url(r'^newbill$', views.newbill, name='newbill'),
url(r'^paid$', views.paid, name='paid'),
url(r'^myopenticket$', views.myopenticket_view, name='myopenticket'),
url(r'^edit_serv$',views.edit_serv_view, name='edit_serv'),
url(r'^edit$',views.edit_view, name='edit'),
url(r'^showallservice/$',views.show_service, name='showallservice'),
url(r'^newservice/$',views.new_service, name='newservice'),
url(r'^delete1$',views.delete_view, name='delete1'),
url(r'^deletebill$',views.deletebill_view, name='deletebill'),
url(r'^all$',views.all, name='all'),
url(r'^all_activation$',views.all_activation, name='all_activation'),
url(r'^all_billing$',views.all_billing, name='all_billing'),
url(r'^all_pending$',views.all_pending, name='all_pending'),
url(r'^credit$',views.credit, name='credit'),

url(r'^prom$',views.prom, name='prom'),

url(r'^no$',views.no, name='no'),

url(r'^signup$',views.signup, name='signup'),
url(r'^index/$', views.Index.as_view(), name='index'),
url(r'^$', views.my_view, name='login'),

url(r'^logout/$', auth_views.logout, {'template_name': 'logout.html'}, name='logout'),
url(r'^admin/', admin.site.urls),
url(r'^allusers$',views.all_users, name='allusers'),
url(r'^employee$',views.employee, name='employee'),
url(r'^add_employee$',views.add_employee, name='add_employee'),
url(r'^employee_prof$',views.employee_prof, name='employee_prof'),








#url(r'^admin$', admin.site.urls),
#url(r'^bootstrap/', TemplateView.as_view(template_name='bootstrap/exmples.html')),
]

mohanad/crm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import connections

from django.db import models
import mysql.connector
# Create your models here.
from datetime import date
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField




class customer(models.Model):
  create = models.DateField(auto_now_add=True,null=True)
  Arabicname = models.CharField(max_length=45)
  
  Englishname = models.CharField(max_length=45,null=True)
  
  email =models.EmailField(null=True)
  service =models.CharField(max_length=45, null=True)
  bundle =models.CharField(max_length=45, null=True)
  speed =models.CharField(max_length=45, null=True)
  period =models.CharField(max_length=45, null=True)
  SecondaryEmail1 =models.EmailField(null=True)
  SecondaryEmail2 =models.EmailField(null=True)
  mobile = models.CharField(max_length=45)
  SecondaryMobile1 = models.CharField(max_length=45,null=True)
  SecondaryMobile2 = models.CharField(max_length=45,null=True)
  Fax = models.CharField(max_length=45,null=True)
  Nationality = models.CharField(max_length=45)
  city = models.CharField(max_length=45)
  username = models.CharField(max_length=45,primary_key=True)
  identity = models.CharField(max_length=45, null=True)
  address  =models.CharField(max_length=45)
  status = models.CharField(max_length=45,default='Activation')
  update = models.CharField(null=True,max_length=45)
  emergency =models.CharField(null=True,max_length=45)
  emergencycount =models.IntegerField(default=0,null=True)
  usercustomer = models.CharField(max_length=45,null=True)
  street = models.CharField(max_length=45,null=True)
  pointing =models.CharField(max_length=45,null=True)
  payment_total = models.CharField(max_length=45,null=True)
  #class Meta:
        #default_permissions = ('add',)
       # permissions = (('can_show_customer','Can show customer'),)

  

class note(models.Model):
  id = models.AutoField(primary_key=True)
  notename =models.CharField(max_length=45,null=True)
  notedate=models.CharField(max_length=45,null=True)
  new_status=models.CharField(max_length=45,null=True)
  report = models.ForeignKey(customer, on_delete=models.CASCADE,null=True)
  usernote = models.CharField(max_length=45,null=True)

class general_note(models.Model):
  id = models.AutoField(primary_key=True)
  generalname =models.CharField(max_length=45,null=True)
  generaldate=models.CharField(max_length=45,null=True)
  generalreport = models.ForeignKey(customer, on_delete=models.CASCADE,null=True)
  usergeneral = models.CharField(max_length=45,null=True)


class edit_note(models.Model):
  id = models.AutoField(primary_key=True)
  editname =models.CharField(max_length=45,null=True)
  editdate=models.CharField(max_length=45,null=True)
 
  editreport = models.ForeignKey(customer, on_delete=models.CASCADE,null=True)
  useredit = models.CharField(max_length=45,null=True)  

from django.db import models

class Post (models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title

class ticket(models.Model):
  id = models.AutoField(primary_key=True)
  tickname =models.CharField(max_length=45,null=True)
  tickdate=models.CharField(max_length=45,null=True)
  tickreport = models.ForeignKey(customer, on_delete=models.CASCADE,null=True)
  tickstatus = models.CharField(max_length=45,default='open')
  close =models.CharField(max_length=45,null=True)
  closedate=models.CharField(max_length=45,null=True)
  useradd = models.CharField(max_length=45,null=True)
  userclose = models.CharField(max_length=45,null=True)
  ticktype = models.CharField(max_length=45,null=True)
  ticksub = models.CharField(max_length=45,null=True)

class replay(models.Model):
  id = models.AutoField(primary_key=True)
  id1 =models.CharField(max_length=45,null=True)
  replaybody =models.CharField(max_length=45,null=True)
  replaydate=models.CharField(max_length=45,null=True)
  replayreport = models.ForeignKey(ticket, on_delete=models.CASCADE,null=True)
  userreplay = models.CharField(max_length=45,null=True)

  


class bills(models.Model):
 id=models.AutoField(primary_key=True)
 billcoast=models.IntegerField(default=1,null=True)
 billdate=models.CharField(max_length=45, null=True)
 cusbill=models.ForeignKey(customer,on_delete=models.CASCADE,null=True)
 billstat=models.CharField(max_length=45,default='Unpaid')
 userbill = models.CharField(max_length=45,null=True)
 userpaid = models.CharField(max_length=45,null=True)
 credit =models.CharField(max_length=45,null=True)
 creditdate=models.CharField(max_length=45,null=True)
 usercredit  =models.CharField(max_length=45,null=True)
 startdate = models.DateTimeField(auto_now_add=False,null=True)
 enddate = models.DateTimeField(auto_now_add=False,null=True)
 instalment=models.CharField(max_length=45,null=True)
 billc = models.CharField(max_length=45,null=True)
 prom = models.CharField(max_length=45,null=True)


class payment(models.Model):
 id=models.BigAutoField(primary_key=True)
 payment=models.IntegerField(null=True)
 paiddate = models.CharField(max_length=45,null=True)
 userpaid = models.CharField(max_length=45,null=True)
 billid = models.CharField(max_length=45,null=True)
 cuspaid=models.ForeignKey(customer,on_delete=models.CASCADE,null=True)

class promotions(models.Model):
  monthnum = models.CharField(max_length=45,null=True)
  cusprom = models.ForeignKey(customer,on_delete=models.CASCADE,null=True)
  userprom = models.CharField(max_length=45,null=True)
  prodate = models.CharField(max_length=45,null=True)
  billid = models.CharField(max_length=45,null=True)


class vas(models.Model):
  sname = models.CharField(primary_key=True,max_length=45)
  scoast = models.IntegerField(default=100)
class vas1(models.Model):
  id = models.AutoField(primary_key=True)
  sname1 = models.CharField(max_length=45)
  vasstat = models.CharField(max_length=45,null=True)
  vasreport = models.ForeignKey(customer, on_delete=models.CASCADE,null=True)
  vstartdate = models.CharField(max_length=45,null=True)
  venddate = models.CharField(max_length=45,null=True)
  uservas = models.CharField(max_length=45,null=True)
  billid = models.CharField(max_length=45,null=True)


class employee1(models.Model):
  eid = models.CharField(max_length=45)
  ename = models.CharField(max_length=45)
  vacation= models.CharField(max_length=45)
  worktime = models.TimeField(default='8:00')
  endtime = models.TimeField(default='16:00')

class vacations(models.Model):
  vdate = models.CharField(max_length=45)
  evdate=models.ForeignKey(employee1,on_delete=models.CASCADE,null=True)

  
  
  

mohanad/templates/all_activation.html
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="mystyle.css">


<meta charset="utf-8">
 <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    



    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />


<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>

   

    <title>All Profile</title>


                 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

    <script src="https://nightly.datatables.net/js/jquery.dataTables.js"></script>
    
    
    <script src="https://nightly.datatables.net/js/dataTables.bootstrap4.min.js "></script>
    
<style>
.fixed-top {
  position: fixed;
  top: 0;
  
}
navbar .nav-item:not(:last-child) {
  margin-right: 35px;
}

.dropdown-toggle::after {
   transition: transform 0.15s linear; 
}

.show.dropdown .dropdown-toggle::after {
  transform: translateY(3px);
}

.dropdown-menu {
  margin-top: 0;
}
.vl {
  border-left: 2px solid tomato; 
  height: 30px;
}

</style>

</head>

  

<body class="" style="background-color:#FAF0E6; ">
<div style="margin-bottom: 100px;">
 {% extends 'headbar.html' %}
 {% block content %}
</div>  
<div class="card  " style="
  background-color: $card-bg;
  border-radius: 50;
  border: 50;
  margin-top: 150px;
box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12);
  transition: box-shadow 0.28s cubic-bezier(0.4, 0, 0.2, 1);
  
  }
}  ">
  <li class="card-body d-inline" style="text-align: center;">
<div class="text-center">  
    
</div>
 <div class="text-left">
<label>number of customer is: {{ results|length }}</label>
</div>
  <div class="card-body"></div>


<div class="container bg">
    <table class="table table-striped table-bordered  dt-responsive nowrap text-center" style="width:10 " id="myTable">
    <thead>
    <tr><th>username</th><th>name</th><th>identity</th><th>mobile</th>
      <th>address</th><th>status</th><th>Email</th><th>created on</th>
      <th>last update</th></tr>
    </thead>

    <tbody>
          {%for r in results%}
        
      <tr>
        <th><form action="{% url 'customer' %}" method="GET" value="{{request.GET.username}}">
<input class="btn" type="hidden" name="username" value="{{r.username}}"/>
<input type="submit" class="btn-link text-dark" name="submit" value="{{r.username}}"/>
</form></th>
<td>{{r.Arabicname}} </td><td>{{r.identity}}</td><td>{{r.mobile}}</td><td>{{r.address}}</td><td>{{r.status}}</td><td>{{r.email}}</td><td>{{r.create}}</td><td>{{r.update}}</td>
      </tr>
   {%endfor%}
    </tbody>
    </table>
</div>
</div>

 <script type="">
    $(document).ready( function () {
  var table = $('#myTable').DataTable({
    "paging":   true,
        "ordering": true,
        "info":     true,
  });
} );
</script>
{%endblock%}
</body>

mohanad/templates/all_pending.html
<!DOCTYPE html>
<html>
<head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="mystyle.css">


<meta charset="utf-8">
 <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    



    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />


<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>

   

    <title>All Profile</title>


                 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

    <script src="https://nightly.datatables.net/js/jquery.dataTables.js"></script>
    
    
    <script src="https://nightly.datatables.net/js/dataTables.bootstrap4.min.js "></script>
    
<style>
.fixed-top {
  position: fixed;
  top: 0;
  
}
navbar .nav-item:not(:last-child) {
  margin-right: 35px;
}

.dropdown-toggle::after {
   transition: transform 0.15s linear; 
}

.show.dropdown .dropdown-toggle::after {
  transform: translateY(3px);
}

.dropdown-menu {
  margin-top: 0;
}
.vl {
  border-left: 2px solid tomato; 
  height: 30px;
}

</style>

</head>

  

<body class="" style="background-color:#FAF0E6; ">
<div style="margin-bottom: 100px;">
 {% extends 'headbar.html' %}
 {% block content %}
</div>  
<div class="card  " style="
  background-color: $card-bg;
  border-radius: 50;
  border: 50;
  margin-top: 150px;
box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12);
  transition: box-shadow 0.28s cubic-bezier(0.4, 0, 0.2, 1);
  
  }
}  ">
  <li class="card-body d-inline" style="text-align: center;">
<div class="text-center">  
    
</div>
 <div class="text-left">
<label>number of customer is: {{ results|length }}</label>
</div>
  <div class="card-body"></div>


<div class="container bg">
    <table class="table table-striped table-bordered  dt-responsive nowrap text-center" style="width:10 " id="myTable">
    <thead>
    <tr><th>username</th><th>name</th><th>identity</th><th>mobile</th>
      <th>address</th><th>status</th><th>Email</th><th>created on</th>
      <th>last update</th></tr>
    </thead>

    <tbody>
          {%for r in results%}
          
        
      <tr>
        <th><form action="{% url 'customer' %}" method="GET" value="{{request.GET.username}}">
<input class="btn" type="hidden" name="username" value="{{r.username}}"/>
<input type="submit" class="btn-link text-dark" name="submit" value="{{r.username}}"/>
</form></th>
<td>{{r.Arabicname}} </td><td>{{r.identity}}</td><td>{{r.mobile}}</td><td>{{r.address}}</td><td>{{r.status}}</td><td>{{r.email}}</td><td>{{r.create}}</td><td>{{r.update}}</td>

      </tr>
   {%endfor%}
     
   

    </tbody>
    </table>
</div>
</div>

 <script type="">
    $(document).ready( function () {
  var table = $('#myTable').DataTable({
    "paging":   true,
        "ordering": true,
        "info":     true,
  });
} );
    
</script>
{%endblock%}
</body>

mohanad/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
 <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <title>Dashboard</title> 
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>



 <link rel="stylesheet" href=  
"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">  
   <!-- CSS -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <title>{% block title %}CRM{% endblock %}</title>
  <style type="text/css">
    .asteriskField {
      display: none;
    }

    form .alert ul li {
      list-style: none;
    }

    form .alert ul {
      padding: 0;
      margin: 0;
    }
  .fixed-top {
  position: fixed;
  top: 0;
  
}
navbar .nav-item:not(:last-child) {
  margin-right: 35px;
}

.dropdown-toggle::after {
   transition: transform 0.15s linear; 
}

.show.dropdown .dropdown-toggle::after {
  transform: translateY(3px);
}

.dropdown-menu {
  margin-top: 0;
}
.vl {
  border-left: 2px solid tomato; 
  height: 30px;
}

</style>

</head>

  

<body class="" style="background-color:#F5F5F5; ">
  {% if user.is_authenticated %}
<div style="margin-bottom: 100px;">
<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top" style="font-size: 18px; ">
    <div class="container">
        <ul class="nav navbar-nav">
          <form class="form-inline  ">
            <li class="nav-item" >

           <a href="{% url 'home' %}" style="font-size:18px"class="btn btn-link">Dashboard</a>
            </li>
           <div class="vl"></div>
        </ul>
      </form>
    </ul>
         <ul class="nav navbar-nav">
          <form class="form-inline  ">
            <li class="nav-item" >
  <li class="nav-item dropdown">

        <a class="nav-link" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Customer
          </a>
        
        <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
          {% if perms.crm.add_customer %} 
 <a href="/newcustomer"style="color: #FF6347;font-size: 18px;" class="dropdown-item"> add new customer</a>
{%endif%}
</form>
{% if perms.crm.add_customer %} 
   <form action="{% url 'all' %}" method="GET" value="">
   <input  type="hidden" name="username" value="" placeholder=" "/>
<input type="submit" style="color: #FF6347;font-size: 18px;" class="dropdown-item" name="submit"  value="All customer" />
 {%endif%}
</form>          

      </li>
  

 </li>
           
        </ul>
                   <div class="vl"></div>

         <ul class="nav navbar-nav ">
          <form class="form-inline  ">
            <li class="nav-item" >
          <li class="nav-item dropdown">
        <a class="nav-link " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User
        </a>
        
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if perms.auth.add_user %} 


<a href="{% url 'signup' %}" style="color: #FF6347;font-size: 18px;" class="dropdown-item">Add new user</a>
</form>
<form action="{% url 'allusers' %}" method="GET" value="">
   
 
<input type="submit" style="color: #FF6347;font-size: 18px;" class="dropdown-item"name="submit"  value="All users" />
 
</form>

{%endif%}
</form>          

      </li>
  
            </li>
             <div class="vl"></div>
            <ul class="nav navbar-nav ">
          <form class="form-inline  ">
            <li class="nav-item" >
          <li class="nav-item dropdown">
        <a class="nav-link " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Employee
        </a>
        
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if perms.auth.add_user %} 


<a href="{% url 'add_employee' %}" style="color: #FF6347;font-size: 18px;" class="dropdown-item">Add employee</a>
</form>
<form action="{% url 'employee' %}" method="GET" value="">
   
 
<input type="submit" style="color: #FF6347;font-size: 18px;" class="dropdown-item"name="submit"  value="All Employee" />
 
</form>

{%endif%}
</form>          

      </li>
  
            </li>
           
        </ul>
        </ul>

</li>

        {% load mathfilters %}
        
      
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link " href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <h4 style="color: #FF6347;font-size: 20px;"> {{ user.username }}</h4>
              </a>
              <div class="dropdown-menu " aria-labelledby="navbarDropdown2">
</form>
</form>
<form action="{% url 'myopenticket' %}" method="GET" value="{{request.GET.user}}" class="form-group position-relative">
<div class="input-group bootstrap-touchspin" id="customer_search_wrapper">
<input name="user" value="{{user}}" type="hidden" class="form-control search-input-field" data-bts-postfix="" name="search">
<div class="dropdown-divider"></div>
<button class="dropdown-item"style="color: #FF6347;font-size: 18px;" type="submit">
My open ticket
</button>
</div>
</form>

<div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}" style="color: #FF6347;font-size: 18px;"><i class="fa fa-power-off" style="font-size:15px ;color:red"></i> Log out</a>

              </div>
            </li>
          </ul>
          
          </form>
      </div>
    </div>
  </nav>

     <script type="text/javascript">
    const $dropdown = $(".dropdown");
const $dropdownToggle = $(".dropdown-toggle");
const $dropdownMenu = $(".dropdown-menu");
const showClass = "show";

$(window).on("load resize", function() {
  if (this.matchMedia("(min-width: 768px)").matches) {
    $dropdown.hover(
      function() {
        const $this = $(this);
        $this.addClass(showClass);
        $this.find($dropdownToggle).attr("aria-expanded", "true");
        $this.find($dropdownMenu).addClass(showClass);
      },
      function() {
        const $this = $(this);
        $this.removeClass(showClass);
        $this.find($dropdownToggle).attr("aria-expanded", "false");
        $this.find($dropdownMenu).removeClass(showClass);
      }
    );
  } else {
    $dropdown.off("mouseenter mouseleave");
  }
});
  </script>
     
  </nav>
<div>
 
        
</div>
  </nav>
{%endif%}

  <li class="card-body d-inline" style="text-align: ;">
  

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

mohanad/templates/create_post.html
<form method="POST" id="post-form">
  {% csrf_token %}
  <div class="form-group">
    <label>Title</label>
    <input type="text" class="form-control" id="title" placeholder="Title">
  </div>
   <div class="form-group">
     <label>Description</label>
     <textarea class="form-control" id="description" placeholder="Description"></textarea>
   </div>
   <button type="submit" class="btn btn-primary">Submit</button>
</form>
<script type="text/javascript">
    $(document).on('submit', '#post-form',function(e){
    $.ajax({
        type:'POST',
        url:'{% url "create_post" %}',
        data:{
            title:$('#title').val(),
            description:$('#description').val(),
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            action: 'post'
        },
       
        error : function(xhr,errmsg,err) {
        console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
    }
    });
});
     success:function(json){
            document.getElementById("post-form").reset();
            $(".posts").prepend('<div class="col-md-6">'+
                '<div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">' +
                    '<div class="col p-4 d-flex flex-column position-static">' +
                        '<h3 class="mb-0">' + json.title + '</h3>' +
                        '<p class="mb-auto">' + json.description + '</p>' +
                    '</div>' +
                '</div>' +
            '</div>' 
            )
        },
</script>

mohanad/templates/index.html
{% extends 'base.html' %}

mohanad/templates/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h2>Password changed with success!</h2>
<p>You may now <a href="{% url 'login' %}">log in</a> again.</p>
{% endblock %}